apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trondelagfylke-no

resources:
  - ../../../base

labels:
  - pairs:
      fintlabs.no/org-id: trondelagfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "trondelagfylke.no"
      
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "trondelagfylke-no.altinn.*"
        
      - op: add
        path: "/spec/env/-"
        value:
          name: "fint.county-organization-number"
          value: "817920632"
      
      - op: add
        path: "/spec/env/-"
        value:
          name: "fint.county-number"
          value: "50"
      
      - op: add
        path: "/spec/env/-"
        value:
          name: "fint.org-id"
          value: "trondelagfylke.no"
          
      - op: add
        path: "/spec/env/-"
        value: 
          name: "fint.altinn.ebevis.api.base-url"
          value: "http://altinn-ebevis-service.default:8080"

      - op: add
        path: "/spec/env/-"
        value: 
          name: "fint.altinn.platform.base-url"
          value: "https://platform.tt02.altinn.no"

      - op: add
        path: "/spec/url/basePath"
        value: "/beta"

      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/api"

    target:
      kind: Application
      name: fint-altinn-service
